src/Entity/Portfolio.php
<?php

namespace App\Entity;

use App\Repository\PortfolioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Symfony\Component\Uid\Uuid;

#[HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: PortfolioRepository::class)]
class Portfolio
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'portfolio', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?float $goal = 0.0;

    #[ORM\Column]
    private ?float $invested = 0.0;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(type: 'uuid')]
    private ?Uuid $uuid = null;

    #[ORM\Column]
    private ?int $numActivePosition = 0;

    #[ORM\Column]
    private ?float $profit = 0.0;

    #[ORM\Column]
    private ?float $totalDividend = 0.0;

    #[ORM\Column]
    private ?float $allocated = 0.0;

    #[ORM\Column]
    private ?float $goalpercentage = 0.0;

    /**
     * @var Collection<int, Position>
     */
    #[ORM\OneToMany(targetEntity: Position::class, mappedBy: 'portfolio')]
    private Collection $positions;

    public function __construct()
    {
        $this->positions = new ArrayCollection();
    }

    #[ORM\PrePersist]
    public function setCreatedAtValue(): void
    {
        $this->created_at = new \DateTimeImmutable();
        $this->setUpdatedAtValue();
    }

    #[ORM\PreUpdate]
    public function setUpdatedAtValue(): void
    {
        $this->updated_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getGoal(): ?float
    {
        return $this->goal;
    }

    public function setGoal(float $goal): static
    {
        $this->goal = $goal;

        return $this;
    }

    public function getInvested(): ?float
    {
        return $this->invested;
    }

    public function setInvested(float $invested): static
    {
        $this->invested = $invested;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function getUuid(): ?Uuid
    {
        return $this->uuid;
    }

    public function setUuid(Uuid $uuid): static
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getNumActivePosition(): ?int
    {
        return $this->numActivePosition;
    }

    public function setNumActivePosition(int $numActivePosition): static
    {
        $this->numActivePosition = $numActivePosition;

        return $this;
    }

    public function getProfit(): ?float
    {
        return $this->profit;
    }

    public function setProfit(float $profit): static
    {
        $this->profit = $profit;

        return $this;
    }

    public function getTotalDividend(): ?float
    {
        return $this->totalDividend;
    }

    public function setTotalDividend(float $totalDividend): static
    {
        $this->totalDividend = $totalDividend;

        return $this;
    }

    public function getAllocated(): ?float
    {
        return $this->allocated;
    }

    public function setAllocated(float $allocated): static
    {
        $this->allocated = $allocated;

        return $this;
    }

    public function getGoalpercentage(): ?float
    {
        return $this->goalpercentage;
    }

    public function setGoalpercentage(float $goalpercentage): static
    {
        $this->goalpercentage = $goalpercentage;

        return $this;
    }

    /**
     * @return Collection<int, Position>
     */
    public function getPositions(): Collection
    {
        return $this->positions;
    }

    public function addPosition(Position $position): static
    {
        if (!$this->positions->contains($position)) {
            $this->positions->add($position);
            $position->setPortfolio($this);
        }

        return $this;
    }

    public function removePosition(Position $position): static
    {
        if ($this->positions->removeElement($position)) {
            // set the owning side to null (unless already changed)
            if ($position->getPortfolio() === $this) {
                $position->setPortfolio(null);
            }
        }

        return $this;
    }
}

src/Controller/Admin/PortfolioController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Portfolio;
use App\Form\PortfolioType;
use App\Repository\PortfolioRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route(path: '/dashboard/portfolio/admin')]
final class PortfolioController extends AbstractController
{
    #[Route(name: 'app_admin_portfolio_controller_index', methods: ['GET'])]
    public function index(PortfolioRepository $portfolioRepository): Response
    {
        return $this->render('portfolio/admin/index.html.twig', [
            'portfolios' => $portfolioRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_portfolio_controller_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $portfolio = new Portfolio();
        $form = $this->createForm(PortfolioType::class, $portfolio);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($portfolio);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_portfolio_controller_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('portfolio/admin/new.html.twig', [
            'portfolio' => $portfolio,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_portfolio_controller_show', methods: ['GET'])]
    public function show(Portfolio $portfolio): Response
    {
        return $this->render('portfolio/admin/show.html.twig', [
            'portfolio' => $portfolio,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_portfolio_controller_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Portfolio $portfolio, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PortfolioType::class, $portfolio);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_portfolio_controller_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('portfolio/admin/edit.html.twig', [
            'portfolio' => $portfolio,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_portfolio_controller_delete', methods: ['POST'])]
    public function delete(Request $request, Portfolio $portfolio, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$portfolio->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($portfolio);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_portfolio_controller_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Portfolio/DividendController.php
<?php

namespace App\Controller\Portfolio;

use App\Entity\Calendar;
use App\Entity\Position;
use App\Entity\Ticker;
use App\Form\CalendarType;
use App\Repository\PaymentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Stopwatch\Stopwatch;
use Pagerfanta\Adapter\ArrayAdapter;
use Pagerfanta\Pagerfanta;

/** @psalm-suppress PropertyNotSetInConstructor */
#[Route(path: '/{_locale<%app.supported_locales%>}/dashboard/portfolio')]
class DividendController extends AbstractController
{
	public const SESSION_KEY = 'portfoliocontroller_session';

	#[
		Route(
			path: '/show/dividends/{id}/{page}',
			name: 'portfolio_show_dividends',
			methods: ['GET']
		)
	]
	public function showDividend(
		Position $position,
		PaymentRepository $paymentRepository,
		int $page = 1
	): Response {
		$ticker = $position->getTicker();
		$calenders = $ticker->getCalendars();

		//$position = $positionRepository->getForPosition($position);
		$dividendRaises = [];

		$reverseCalendars = array_reverse($calenders->toArray(), true);
		// Cals start with latest and descent
		/**
		 * @var Calendar $calendar
		 */
		foreach ($reverseCalendars as $index => $calendar) {
			$dividendRaises[$index] = 0;
			if (
				$calendar->getDividendType() === Calendar::REGULAR &&
				stripos($calendar->getDescription() ?? '', 'Extra') === false
			) {
				if (isset($oldCal) && $oldCal->getCashAmount() > 0) {
					$oldCash = $oldCal->getCashAmount(); // previous
					$dividendRaises[$index] =
						(($calendar->getCashAmount() - $oldCash) / $oldCash) *
						100;
				}
				$oldCal = $calendar;
			}
		}

		$dividends = $paymentRepository->getSumDividends([$ticker->getId()]);
		$dividend = 0;
		if (!empty($dividends) && $ticker->getId() != null) {
			$dividend = $dividends[$ticker->getId()];
		}
		$calendarsCount = $calenders->count();

		$adapter = new ArrayAdapter($calenders->toArray());
		$pager = new Pagerfanta($adapter);
		$pager->setMaxPerPage(10);
		$pager->setCurrentPage($page);

		return $this->render('portfolio/show/dividend/_dividend.html.twig', [
			'ticker' => $ticker,
			'position' => $position,
			'dividend' => $dividend,
			'pager' => $pager,
			'calendarsCount' => $calendarsCount,
			'dividendRaises' => $dividendRaises,
		]);
	}

	#[
		Route(
			path: '/create_dividend/{ticker?}',
			name: 'portfolio_calendar_new',
			methods: ['GET', 'POST']
		)
	]
	public function createDividend(
		Request $request,
		EntityManagerInterface $entityManager,
		?Ticker $ticker,
		?Position $position
	) {
		$calendar = new Calendar();
		if ($ticker != null) {
			$calendar->setTicker($ticker);
		}
		$form = $this->createForm(CalendarType::class, $calendar);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$calendar->setSource(Calendar::SOURCE_MANUEL);
			$entityManager->persist($calendar);
			$entityManager->flush();

			return $this->redirectToRoute('portfolio_show_dividends', [
				'id' => $position->getId(),
				'page' => 1,
			]);
		}

		return $this->render(
			'portfolio/show/dividend/_form_dividend_create.html.twig',
			[
				'calendar' => $calendar,
				'position' => $position,
				'ticker' => $ticker,
				'form' => $form->createView(),
			]
		);
	}

	#[
		Route(
			path: '/delete_dividend/{calendar}/{position}',
			name: 'portfolio_calendar_delete',
			methods: ['POST']
		)
	]
	public function deleteDividend(
		Request $request,
		EntityManagerInterface $entityManager,
		Calendar $calendar,
		Position $position
	): Response {
		if (
			$this->isCsrfTokenValid(
				'delete' . $calendar->getId(),
				$request->request->get('_token')
			)
		) {
			if ($calendar->getPayments()->isEmpty()) {
				$entityManager->remove($calendar);
				$entityManager->flush();
			} else {
				$this->addFlash(
					'notice',
					'Can not remove calendar because it has payments linked to it.'
				);
			}
		}

		return $this->redirectToRoute('portfolio_show_dividends', [
			'id' => $position->getId(),
			'page' => 1,
		]);
	}
}

src/Controller/Portfolio/PaymentController.php
<?php

namespace App\Controller\Portfolio;

use App\Entity\Payment;
use App\Entity\Position;
use App\Entity\Transaction;
use App\Form\PaymentType;
use App\Form\TransactionPieType;
use App\Repository\PaymentRepository;
use App\Repository\TransactionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Stopwatch\Stopwatch;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;

/** @psalm-suppress PropertyNotSetInConstructor */
#[Route(path: '/{_locale<%app.supported_locales%>}/dashboard/portfolio')]
class PaymentController extends AbstractController
{
	public const SESSION_KEY = 'portfoliocontroller_session';

	#[
		Route(
			path: '/create_payment/{position?}',
			name: 'portfolio_create_payment',
			methods: ['GET']
		)
	]
	public function createPayment(
		Request $request,
		EntityManagerInterface $entityManager,
		Position $position
	) {
		$payment = new Payment();
		$payment->setPosition($position);
		$payment->setTicker($position->getTicker());

		$form = $this->createForm(PaymentType::class, $payment);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$entityManager->persist($payment);
			$entityManager->flush();

			return $this->redirectToRoute('portfolio_show_payments', [
				'id' => $position->getId(),
				'page' => 1,
			]);
		}

		return $this->render(
			'portfolio/show/payment/_form_payment_create.html.twig',
			[
				'payment' => $payment,
				'position' => $position,
				'ticker' => $position->getTicker(),
				'form' => $form->createView(),
			]
		);
	}

		#[
		Route(
			path: '/edit_payment/{payment}/{page}',
			name: 'portfolio_edit_payment',
			methods: ['GET', 'POST']
		)
	]
	public function editPayment(
		Request $request,
		EntityManagerInterface $entityManager,
		PaymentRepository $paymentRepository,
		Payment $payment,
		int $page = 1
	) {
		$form = $this->createForm(PaymentType::class, $payment);
		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$entityManager->persist($payment);
			$entityManager->flush();

			return $this->redirectToRoute('portfolio_show_payments', [
				'id' => $payment->getPosition()->getId(),
				'page' => 1,
			]);
		}

		$ticker = $payment->getTicker();
		$position = $payment->getPosition();

		$dividends = $paymentRepository->getSumDividends([$ticker->getId()]);
		$dividend = 0;
		if (!empty($dividends) && $ticker->getId() != null) {
			$dividend = $dividends[$ticker->getId()];
		}

		$queryBuilder = $paymentRepository->getForPositionQueryBuilder(
			$position
		);
		$adapter = new QueryAdapter($queryBuilder);
		$pager = new Pagerfanta($adapter);
		$pager->setMaxPerPage(10);
		$pager->setCurrentPage($page);

		return $this->render(
			'portfolio/show/payment/_form_payment_edit.html.twig',
			[
				'edit_payment' => $payment,
				'pager' => $pager,
				'position' => $position,
				'dividend' => $dividend,
				'form' => $form->createView(),
			]
		);
	}

	#[
		Route(
			path: '/delete_payment/{payment}',
			name: 'portfolio_payment_delete',
			methods: ['POST']
		)
	]
	public function deletePayment(
		Request $request,
		EntityManagerInterface $entityManager,
		Payment $payment,
		Position $position
	): Response {
		if (
			$this->isCsrfTokenValid(
				'delete' . $payment->getId(),
				$request->request->get('_token')
			)
		) {
			$entityManager->remove($payment);
			$entityManager->flush();

			$this->addFlash('notice', 'Payment removed.');
		}
		return $this->redirectToRoute('portfolio_show_dividends', [
			'id' => $position->getId(),
			'page' => 1,
		]);
	}

	#[
		Route(
			path: '/show/payments/{id}/{page}',
			name: 'portfolio_show_payments',
			methods: ['GET']
		)
	]
	public function showPayments(
		Position $position,
		PaymentRepository $paymentRepository,
		int $page = 1
	): Response {
		$ticker = $position->getTicker();

		$payments = $position->getPayments();
		$dividends = $paymentRepository->getSumDividends([$ticker->getId()]);
		$dividend = 0;
		if (!empty($dividends) && $ticker->getId() != null) {
			$dividend = $dividends[$ticker->getId()];
		}

		$queryBuilder = $paymentRepository->getForPositionQueryBuilder(
			$position
		);
		$adapter = new QueryAdapter($queryBuilder);
		$pager = new Pagerfanta($adapter);
		$pager->setMaxPerPage(10);
		$pager->setCurrentPage($page);

		return $this->render('portfolio/show/payment/_payments.html.twig', [
			'pager' => $pager,
			'position' => $position,
			'payments' => $payments,
			'dividend' => $dividend,
		]);
	}

		#[
		Route(
			path: '/updatepie/{id}',
			name: 'portfolio_update_pie',
			methods: ['POST', 'GET']
		)
	]
	public function updatePie(
		Request $request,
		Transaction $transaction,
		EntityManagerInterface $entityManager,
		TransactionRepository $transactionRepository
	): Response {
		$transaction = $transactionRepository->find($transaction->getId());

		$form = $this->createForm(TransactionPieType::class, $transaction, [
			'action' => $this->generateUrl('portfolio_update_goal'),
		]);

		$form->handleRequest($request);
		if ($form->isSubmitted() && $form->isValid()) {
			$entityManager->persist($transaction);
			$entityManager->flush();

			return $this->render('portfolio/show/transaction/_transaction_pie.html.twig', [
				'transaction' => $transaction,
			]);
		}

		return $this->render('portfolio/show/_form_update_pie.html.twig', [
			'transaction' => $transaction,
			'form' => $form,
			'formTarget' => 'update-pie-' . $transaction->getId(),
		]);
	}
}

templates/portfolio/show/_form_update_pie.html.twig
<turbo-frame id="update-pie-{{ transaction.id}}">
{{ form_start(form, {action: path('portfolio_update_pie', {'id' : transaction.id}), attr: { "data-controller": "inline-edit", "data-turbo-frame": formTarget  }}) }}
    <select name="{{ field_name(form.pie) }}" data-inline-edit-target="input"
            class="border border-gray-400 rounded-lg"
            data-action="blur->inline-edit#submitForm keydown.enter->inline-edit#submitForm:prevent keydown.esc->inline-edit#abort">
        <option value="">{{ field_label(form.pie) }}</option>
        {% for label, value in field_choices(form.pie) %}<option value="{{ value }}">{{ label }}</option>{% endfor %}
    </select>
{{ form_end(form) }}
</turbo-frame>

templates/portfolio/show/_growth.html.twig
<turbo-frame id="portfolio_tab_results">

<div class="flex flex-col">
	<div class="mx-auto" style="width:900px;height:600px">
		{{ render_chart(chartYield, {
					'data-controller': 'chartjs-add-percentage'
				}) }}
	</div>
	<div class="mx-auto" style="width:900px;height:600px">
		{{ render_chart(chartPayout, {
				'data-controller': 'chartjs-add-euro-sign'
			}) }}
	</div>
</div>

</turbo-frame>

templates/portfolio/show/_research.html.twig
<turbo-frame id="portfolio_tab_results">
<div class="flex flex-col">
    <div class="flex flex-col border border-gray-400 w-full rounded-lg p-4 mb-4">
        <div class="mb-4">
            <twig:Head variant="h5">
                {{ 'Company details'|trans }}
            </twig:Head>
        </div>
        <div class="normal-case">{{ ticker.description|raw }}</div>
        <hr class="mt-2 mb-4">
        <div class="mt-2">
            <twig:Button tag="a"
                         href="{{ path('ticker_edit', {'id': ticker.id}) }}"
                         data-turbo-frame="_top">
                <i class="far fa-edit"></i>
            </twig:Button>
        </div>
    </div>
    <div>
        {% for research in pager %}
            <div class="mb-4">
                <div class="flex flex-col border border-gray-400 w-full rounded-lg">
                    <div class="mb-4 p-4">
                        <twig:Head variant="h5">
                            {{ research.title }}
                        </twig:Head>
                    </div>
                    <div class="normal-case mb-4 flex flex-col p-4">
                        <div class="mb-4">
                            <p>{{ research.info|raw }}</p>
                            {% if research.attachments and research.attachments|length > 0 %}
                                <div class="mt-4 py-4">
                                    {% for doc in research.attachments %}
                                        <div class="mb-2">
                                            <twig:Button tag="a"
                                                         href="{{ asset('uploads/documents/' ~ doc.attachmentName) }}"
                                                         data-turbo-frame="_blank"
                                                         target='_blank'>
                                                <i class="fa fa-download"></i>
                                                {{ doc.label }}
                                            </twig:Button>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <hr class="mt-2 mb-4">
                        <div class="mb-4">
                            <twig:Button tag="a"
                                         href="{{ path('research_edit', {'id': research.id}) }}"
                                         data-turbo-frame="_top">
                                <i class="far fa-edit"></i>
                            </twig:Button>
                        </div>
                    </div>
                    <div class="flex w-full bg-gray-100 rounded-b-lg p-4">
                        {{ 'Created'|trans }}:&nbsp;
                        <strong>{{ research.createdAt ? research.createdAt|date('Y-m-d H:i:s', 'Europe/Amsterdam') |format_datetime('full','medium', locale: 'nl') : '-' }}</strong>.
                        {{ 'Modified'|trans }}:&nbsp;
                        <strong>{{ research.updatedAt ? research.updatedAt|date('Y-m-d H:i:s', 'Europe/Amsterdam') |format_datetime('full','medium', locale: 'nl') : '-' }}</strong>
                    </div>
                </div>
            </div>
        {% else %}
            no records found
        {% endfor %}
    </div>
    <div class="flex mt-2" data-controller="tooltip">
        <twig:Button tag="a"
                     href="{{ path('research_new', {'ticker': ticker.id}) }}"
                     data-turbo-frame="_top"
                     data-tooltip-target="element"
                     data-action="mouseenter->tooltip#show mouseleave->tooltip#hide">
            <i class="fab fa-searchengin"></i>
            <div class="tooltip" role="tooltip" data-tooltip-target="tooltip">
                {{ 'Add research'|trans }}
                <div class="arrow" data-tooltip-target="tooltipArrow"></div>
            </div>
        </twig:Button>
    </div>
</div>
</turbo-frame>